[package]
name = "rust-nds-template"
version = "0.0.1"
authors = ["Your Name Here <no-reply@example.com>"]
edition = "2018"

[profile.release]
lto = "fat"

[profile.dev]
lto = false
opt-level = 1

[dependencies]
# nds = { git = "https://github.com/BlueTheDuck/nds-rs.git" }
nds = { path = "../nds-rs" }

[build-dependencies]
cc = "1.0"