[build]
target = "armv5te-none-eabi"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.armv5te-none-eabi]
# runner = "melonDS"
rustflags = [
      "--cfg", "portable_atomic_no_outline_atomics",

      "-Ctarget-cpu=arm946e-s", "-Csoft-float=yes",

      "-Clink-args=-Wl,--start-group -lc -lgcc -Wl,--end-group",
      "-Clink-arg=-specs=/opt/wonderful/thirdparty/blocksds/core/sys/crts/ds_arm9.specs",

      # # Some debugging flags
      # "-Clink-arg=-Wl,-Map=target/nds.map",
      # "-Clink-arg=-Wl,--verbose",
      # "--print", "link-args"
]
linker = "arm-none-eabi-gcc"
